# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 260ae0ad52850d19c126e3ea59064e9500e662f34e5302e3073a864db894130c6fd94be63fed9fda417a8c4adcef5f72462e144f0ac8fdfee7df82bf8bd3d497

test:
  secret_key_base: 06555727be25ff0eddc9af1bc6a8ff32ae07ae5c2eb8c680637207f03f3897f59abf05c324e6f9092dbf3bfe7ce467fb7fb40bca0c1a9b94f61e3e306aab478f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
